#!/bin/bash

# config_all.sh - Generate .env.yaml files for all cloud functions
# This script reads the main .env file and creates .env.yaml files
# in each subdirectory that needs environment variables for deployment

set -e  # Exit on error

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "========================================"
echo "  Cloud Functions .env.yaml Generator"
echo "========================================"
echo ""

# Check if .env file exists
if [ ! -f "$ENV_FILE" ]; then
    echo -e "${RED}Error: .env file not found at $ENV_FILE${NC}"
    exit 1
fi

echo -e "${GREEN}✓${NC} Found .env file"

# Parse .env file - bash 3.2 compatible
# Create temporary file to store env vars
ENV_TEMP=$(mktemp)
trap "rm -f $ENV_TEMP" EXIT

var_count=0
while IFS='=' read -r key value; do
    # Skip empty lines and comments
    [[ -z "$key" || "$key" =~ ^#.*$ ]] && continue
    # Remove leading/trailing whitespace
    key=$(echo "$key" | xargs)
    value=$(echo "$value" | xargs)
    # Store in temp file
    if [ -n "$key" ] && [ -n "$value" ]; then
        echo "$key=$value" >> "$ENV_TEMP"
        ((var_count++))
    fi
done < "$ENV_FILE"

echo -e "${GREEN}✓${NC} Parsed $var_count environment variables"
echo ""

# Function to get value for a key from temp file
get_env_value() {
    local search_key=$1
    grep "^$search_key=" "$ENV_TEMP" | cut -d'=' -f2-
}

# Function to determine which env vars are needed for each function
# Based on function name and common patterns
get_relevant_vars() {
    local func_name=$1

    case "$func_name" in
        *stripe*|*payment*)
            echo "STRIPE_SECRET_KEY STRIPE_WEBHOOK_SECRET"
            ;;
        *discord*|*webhook*)
            echo "FALECONOSCO_WEBHOOK ERROS_WEBHOOK DENUNCIAR_WEBHOOK"
            ;;
        *algolia*|*search*)
            echo "ALGOLIA_ID ALGOLIA_KEY"
            ;;
        *)
            # For unknown functions, include all variables (safer default)
            cut -d'=' -f1 "$ENV_TEMP" | xargs
            ;;
    esac
}

# Function to create .env.yaml file
create_env_yaml() {
    local dir=$1
    local func_name=$(basename "$dir")
    local output_file="$dir/.env.yaml"

    # Get relevant variables for this function
    local relevant_vars=($(get_relevant_vars "$func_name"))

    # Create .env.yaml file
    echo "# Auto-generated by config_all.sh" > "$output_file"
    echo "# Source: .env" >> "$output_file"
    echo "# Generated: $(date)" >> "$output_file"
    echo "" >> "$output_file"

    local var_count=0
    for key in "${relevant_vars[@]}"; do
        local value=$(get_env_value "$key")
        if [ -n "$value" ]; then
            echo "$key: \"$value\"" >> "$output_file"
            ((var_count++))
        fi
    done

    if [ $var_count -gt 0 ]; then
        echo -e "  ${GREEN}✓${NC} Created/Updated: $output_file ($var_count variables)"
        return 0
    else
        echo -e "  ${YELLOW}⚠${NC}  Skipped: $output_file (no matching variables)"
        rm -f "$output_file"
        return 1
    fi
}

# Scan for functions that need .env.yaml files
echo "Scanning for cloud functions..."
echo ""

processed=0
skipped=0

for dir in "$SCRIPT_DIR"/*/; do
    # Skip if not a directory
    [ ! -d "$dir" ] && continue

    package_json="$dir/package.json"

    # Skip if no package.json
    [ ! -f "$package_json" ] && continue

    # Check if deploy script uses --env-vars-file
    if grep -q "\-\-env-vars-file.*\.env\.yaml" "$package_json" 2>/dev/null; then
        func_name=$(basename "$dir")
        echo "Processing: $func_name"
        if create_env_yaml "$dir"; then
            ((processed++))
        else
            ((skipped++))
        fi
    fi
done

echo ""
echo "========================================"
echo -e "${GREEN}✓${NC} Processed: $processed functions"
[ $skipped -gt 0 ] && echo -e "${YELLOW}⚠${NC}  Skipped: $skipped functions"
echo "========================================"
echo ""
echo "Done! You can now deploy your functions."
echo ""

# Optional: List created files
if [ $processed -gt 0 ]; then
    echo "Created/Updated files:"
    find "$SCRIPT_DIR" -maxdepth 2 -name ".env.yaml" -type f | while read -r file; do
        rel_path=$(echo "$file" | sed "s|$SCRIPT_DIR/||")
        echo "  - $rel_path"
    done
    echo ""
fi
