import { NativeStackScreenProps } from "@react-navigation/native-stack"
import { SaleStackParamList } from "../types"

export type SelectSaleCategoryScreenProps = NativeStackScreenProps<SaleStackParamList, 'SelectSaleCategory'>
export type SelectSaleTagsScreenProps = NativeStackScreenProps<SaleStackParamList, 'SelectSaleTags'>
export type InsertSaleTitleScreenProps = NativeStackScreenProps<SaleStackParamList, 'InsertSaleTitle'>
export type InsertItemNameScreenProps = NativeStackScreenProps<SaleStackParamList, 'InsertItemName'>
export type InsertItemDescriptionScreenProps = NativeStackScreenProps<SaleStackParamList, 'InsertItemDescription'>
export type InsertSalePictureScreenProps = NativeStackScreenProps<SaleStackParamList, 'InsertSalePicture'>
export type SalePicturePreviewScreenProps = NativeStackScreenProps<SaleStackParamList, 'SalePicturePreview'>
export type SelectPaymentTypeScreenProps = NativeStackScreenProps<SaleStackParamList, 'SelectPaymentType'>
export type InsertSaleValueScreenProps = NativeStackScreenProps<SaleStackParamList, 'InsertSaleValue'>
export type InsertExchangeValueScreenProps = NativeStackScreenProps<SaleStackParamList, 'InsertExchangeValue'>
export type InsertSaleLocationScreenProps = NativeStackScreenProps<SaleStackParamList, 'InsertSaleLocation'>
export type SelectLocationViewScreenProps = NativeStackScreenProps<SaleStackParamList, 'SelectLocationView'>
export type LocationViewPreviewScreenProps = NativeStackScreenProps<SaleStackParamList, 'LocationViewPreview'>
export type SelectDeliveryMethodScreenProps = NativeStackScreenProps<SaleStackParamList, 'SelectDeliveryMethod'>
export type SelectSaleFrequencyScreenProps = NativeStackScreenProps<SaleStackParamList, 'SelectSaleFrequency'>
export type SelectDaysOfWeekScreenProps = NativeStackScreenProps<SaleStackParamList, 'SelectDaysOfWeek'>