declare module '@env' {
	export const ENVIRONMENT: string

	export const FIREBASE_apiKey: string
	export const FIREBASE_authDomain: string
	export const FIREBASE_projectId: string
	export const FIREBASE_storageBucket: string
	export const FIREBASE_messagingSenderId: string
	export const FIREBASE_appId: string
	export const FIREBASE_measurementId: string
	export const FIREBASE_databaseURL: string
	export const FIREBASE_smas_databaseURL: string
	export const FIREBASE_CLOUD_URL: string
	export const MAPS_API: string
	export const ALGOLIA_ID: string
	export const ALGOLIA_KEY: string

	export const PROD_FIREBASE_apiKey: string
	export const PROD_FIREBASE_authDomain: string
	export const PROD_FIREBASE_databaseURL: string
	export const PROD_FIREBASE_projectId: string
	export const PROD_FIREBASE_storageBucket: string
	export const PROD_FIREBASE_messagingSenderId: string
	export const PROD_FIREBASE_appId: string
	export const PROD_FIREBASE_measurementId: string
	export const PROD_FIREBASE_CLOUD_URL: string
	export const PROD_ALGOLIA_ID: string
	export const PROD_ALGOLIA_KEY: string
	export const PROD_AUTH_EXPO_CLIENT_ID: string
	export const PROD_AUTH_CLIENT_ID: string
	export const PROD_AUTH_ANDROID_CLIENT_ID: string
	export const PROD_AUTH_IOS_CLIENT_ID: string
	export const PROD_MAPS_API: string
	export const PROD_STRIPE_PUBLISHABLE_KEY: string
	export const PROD_STRIPE_SECRET_KEY: string
	export const PROD_STRIPE_API_URL: string

	export const AUTH_EXPO_CLIENT_ID: string
	export const AUTH_ANDROID_CLIENT_ID: string
	export const AUTH_IOS_CLIENT_ID: string
	export const DENUNCIAR_WEBHOOK: string
	export const ERROS_WEBHOOK: string
	export const FALECONOSCO_WEBHOOK: string
	export const NOTION_FALECONOSCO_KEY: string
	export const NOTION_FALECONOSCO_ID: string
	export const NOTION_APPICONS_ID: string
	export const NOTION_APPICONS_KEY: string
	export const DSN_SENTRY: string
	export const STRIPE_PUBLISHABLE_KEY: string
	export const STRIPE_SECRET_KEY: string
	export const STRIPE_API_URL: string
	export const SENTRY_AUTH_TOKEN: string
}
