declare module '@env' {
	export const FIREBASE_apiKey: string
	export const FIREBASE_authDomain: string
	export const FIREBASE_databaseURL: string
	export const FIREBASE_projectId: string
	export const FIREBASE_storageBucket: string
	export const FIREBASE_messagingSenderId: string
	export const FIREBASE_appId: string
	export const FIREBASE_measurementId: string
	export const FIREBASE_CLOUD_URL: string
	export const MAPS_API: string
	export const DENUNCIAR_WEBHOOK: string
	export const ERROS_WEBHOOK: string
	export const FALECONOSCO_WEBHOOK: string
	export const ALGOLIA_ID: string
	export const ALGOLIA_KEY: string
	export const NOTION_FALECONOSCO_KEY: string
	export const NOTION_FALECONOSCO_ID: string
	export const NOTION_APPICONS_ID: string
	export const NOTION_APPICONS_KEY: string
	export const DSN_SENTRY: string
}
