import { NativeStackScreenProps } from '@react-navigation/native-stack'

import { SocialImpactStackParamList } from '../types'

export type InsertSocialImpactTitleScreenProps = NativeStackScreenProps<SocialImpactStackParamList, 'InsertSocialImpactTitle'>
export type InsertSocialImpactDescriptionScreenProps = NativeStackScreenProps<SocialImpactStackParamList, 'InsertSocialImpactDescription'>
export type InsertSocialImpactPictureScreenProps = NativeStackScreenProps<SocialImpactStackParamList, 'InsertSocialImpactPicture'>
export type SocialImpactPicturePreviewScreenProps = NativeStackScreenProps<SocialImpactStackParamList, 'SocialImpactPicturePreview'>
export type SelectSocialImpactCategoryScreenProps = NativeStackScreenProps<SocialImpactStackParamList, 'SelectSocialImpactCategory'>
export type SelectSocialImpactTagsScreenProps = NativeStackScreenProps<SocialImpactStackParamList, 'SelectSocialImpactTags'>
export type SelectSocialImpactExhibitionRangeScreenProps = NativeStackScreenProps<SocialImpactStackParamList, 'SelectSocialImpactExhibitionRange'>
export type SelectSocialImpactRangeScreenProps = NativeStackScreenProps<SocialImpactStackParamList, 'SelectSocialImpactRange'>
export type InsertSocialImpactLocationScreenProps = NativeStackScreenProps<SocialImpactStackParamList, 'InsertSocialImpactLocation'>
export type SelectSocialImpactLocationViewScreenProps = NativeStackScreenProps<SocialImpactStackParamList, 'SelectSocialImpactLocationView'>
export type SocialImpactLocationViewPreviewScreenProps = NativeStackScreenProps<SocialImpactStackParamList, 'SocialImpactLocationViewPreview'>
export type SelectSocialImpactExhibitionPlaceScreenProps = NativeStackScreenProps<SocialImpactStackParamList, 'SelectSocialImpactExhibitionPlace'>
export type SelectSocialImpactFrequencyScreenProps = NativeStackScreenProps<SocialImpactStackParamList, 'SelectSocialImpactFrequency'>
export type SelectDaysOfWeekScreenProps = NativeStackScreenProps<SocialImpactStackParamList, 'SelectDaysOfWeek'>
export type InsertSocialImpactStartDateScreenProps = NativeStackScreenProps<SocialImpactStackParamList, 'InsertSocialImpactStartDate'>
export type InsertOpeningHourScreenProps = NativeStackScreenProps<SocialImpactStackParamList, 'InsertOpeningHour'>
export type InsertClosingHourScreenProps = NativeStackScreenProps<SocialImpactStackParamList, 'InsertClosingHour'>
export type SelectSocialImpactRepeatScreenProps = NativeStackScreenProps<SocialImpactStackParamList, 'SelectSocialImpactRepeat'>
